name: ci-cd Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install setuptools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # will be un commented after we create the test cases !
    # - name: Run tests
    #   run: |
    #     pytest
